### ISSUE TITLE
failure to build app

### ISSUE THREAD

**Issue by davidascher** [darrinhenein/cupcake-dashboard#21]
I'm following the readme, and getting a failure at step 6, "grunt build in /app"

```
acai:app davida$ grunt build

/Users/davida/src/cupcake-dashboard/app/node_modules/grunt/node_modules/findup-sync/lib/findup-sync.js:33
    }).flatten().uniq().value();
       ^
TypeError: Object Gruntfile.js has no method 'flatten'
    at Object.module.exports [as findup] (/Users/davida/src/cupcake-dashboard/app/node_modules/grunt/node_modules/findup-sync/lib/findup-sync.js:33:8)
    at Task.task.init (/Users/davida/src/cupcake-dashboard/app/node_modules/grunt/lib/grunt/task.js:420:16)
    at Object.grunt.tasks (/Users/davida/src/cupcake-dashboard/app/node_modules/grunt/lib/grunt.js:113:8)
    at Object.module.exports [as cli] (/Users/davida/src/cupcake-dashboard/app/node_modules/grunt/lib/grunt/cli.js:38:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/grunt-cli/bin/grunt:45:20)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

**Comment by toolness** [comment]
See #35 for information on how I got around this one...
